# Generated by Django 5.2.8 on 2025-11-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='composition',
            field=models.TextField(blank=True, help_text='Перечислите ингредиенты', verbose_name='Состав'),
        ),
    ]
